
services:
  tarantool1:
    image: tarantool/tarantool:2.11.2
    container_name: benakun_tarantool
    environment:
      TARANTOOL_USER_NAME: "benakunT"
      TARANTOOL_USER_PASSWORD: "benakunPT"
      TT_READAHEAD: '1632000' # 10x
      TT_VINYL_MEMORY: '268435456' # 20x
      TT_VINYL_CACHE: '2684354560' # 20x
      TT_NET_MSG_MAX: '76800' # 100x
      TT_MEMTX_MEMORY: '268435456' # 1x
      TT_VINYL_PAGE_SIZE: '8192' # 1x
    volumes:
      - ./_tmpdb/var_lib_tarantool:/var/lib/tarantool
    ports:
      - "3302:3301"

  clickhouse1:
    image: clickhouse/clickhouse-server:23.11.2.11
    # previously: 23.4.2.11
    # next: 24.1
    container_name: benakun_clickhouse
    ports:
      - "8124:8123"
      - "9001:9000"
    environment:
      CLICKHOUSE_USER: "benakunC"
      CLICKHOUSE_PASSWORD: "benakunPC"
      CLICHOUSE_DB: "benakunDB"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./_tmpdb/var_lib_clickhouse:/var/lib/clickhouse

  mailhog1:
    image: mailhog/mailhog
    container_name: benakun_mailhog
    ports:
      - "1026:1025"
      - "8026:8025"