package presentation

// Code generated by 1_codegen_test.go DO NOT EDIT.

import (
	"benakun/domain"
)

var allCommands = []string{
	domain.DataEntryDashboardAction,
	domain.GuestAutoLoginAction,
	domain.GuestDebugAction,
	domain.GuestExternalAuthAction,
	domain.GuestForgotPasswordAction,
	domain.GuestLoginAction,
	domain.GuestOauthCallbackAction,
	domain.GuestRegisterAction,
	domain.GuestResendVerificationEmailAction,
	domain.GuestResetPasswordAction,
	domain.GuestVerifyEmailAction,
	domain.ReportViewerDashboardAction,
	domain.SuperAdminDashboardAction,
	domain.SuperAdminTenantManagementAction,
	domain.SuperAdminUserManagementAction,
	domain.TenantAdminBankAccountsAction,
	domain.TenantAdminBudgetingAction,
	domain.TenantAdminCoaAction,
	domain.TenantAdminCreateBudgetPlanAction,
	domain.TenantAdminCreateCoaChildAction,
	domain.TenantAdminCreateOrganizationChildAction,
	domain.TenantAdminDashboardAction,
	domain.TenantAdminDeleteCoaChildAction,
	domain.TenantAdminDeleteOrganizationChildAction,
	domain.TenantAdminGetBudgetPlansAction,
	domain.TenantAdminMoveOrganizationChildAction,
	domain.TenantAdminOrganizationAction,
	domain.TenantAdminRestoreCoaChildAction,
	domain.TenantAdminRestoreOrganizationChildAction,
	domain.TenantAdminTransactionAction,
	domain.TenantAdminUpdateBudgetPlanAction,
	domain.TenantAdminUpdateCoaChildAction,
	domain.TenantAdminUpdateOrganizationChildAction,
	domain.UserAutoLoginLinkAction,
	domain.UserChangePasswordAction,
	domain.UserCreateCompanyAction,
	domain.UserLogoutAction,
	domain.UserProfileAction,
	domain.UserResponseInvitationAction,
	domain.UserSessionKillAction,
	domain.UserSessionsActiveAction,
	domain.UserUpdateProfileAction,
}

// Code generated by 1_codegen_test.go DO NOT EDIT.
