package presentation

// Code generated by 1_codegen_test.go DO NOT EDIT.

import (
	"benakun/domain"
)

var allCommands = []string{
	domain.DataEntryDashboardAction,
	domain.DataEntryTransactionEntryAction,
	domain.GuestAutoLoginAction,
	domain.GuestDebugAction,
	domain.GuestExternalAuthAction,
	domain.GuestForgotPasswordAction,
	domain.GuestLoginAction,
	domain.GuestOauthCallbackAction,
	domain.GuestRegisterAction,
	domain.GuestResendVerificationEmailAction,
	domain.GuestResetPasswordAction,
	domain.GuestVerifyEmailAction,
	domain.ReportViewerDashboardAction,
	domain.SuperAdminAccessLogAction,
	domain.SuperAdminDashboardAction,
	domain.SuperAdminTenantManagementAction,
	domain.SuperAdminUserManagementAction,
	domain.TenantAdminBankAccountsAction,
	domain.TenantAdminBudgetingAction,
	domain.TenantAdminCoaAction,
	domain.TenantAdminDashboardAction,
	domain.TenantAdminDeleteOrganizationChildAction,
	domain.TenantAdminInventoryChangesAction,
	domain.TenantAdminInventoryChangesProductAction,
	domain.TenantAdminLocationsAction,
	domain.TenantAdminMoveOrganizationChildAction,
	domain.TenantAdminOrganizationAction,
	domain.TenantAdminProductsAction,
	domain.TenantAdminRestoreOrganizationChildAction,
	domain.TenantAdminTransactionAction,
	domain.TenantAdminTransactionTemplateAction,
	domain.TenantAdminUpsertOrganizationChildAction,
	domain.UserAutoLoginLinkAction,
	domain.UserChangePasswordAction,
	domain.UserCreateCompanyAction,
	domain.UserLogoutAction,
	domain.UserProfileAction,
	domain.UserResponseInvitationAction,
	domain.UserSessionKillAction,
	domain.UserSessionsActiveAction,
	domain.UserUpdateProfileAction,
}

// Code generated by 1_codegen_test.go DO NOT EDIT.
